CREATE TABLE PBI.BalanceSheetStructure (
 Level1 VARCHAR(100)
,Level2 VARCHAR(100)
,Ord TINYINT
)

INSERT INTO PBI.BalanceSheetStructure VALUES('1. NON CURRENT ASSETS','Signs','1')
INSERT INTO PBI.BalanceSheetStructure VALUES('1. NON CURRENT ASSETS','Equipment','2')
INSERT INTO PBI.BalanceSheetStructure VALUES('1. NON CURRENT ASSETS','Furniture and fittings','3')
INSERT INTO PBI.BalanceSheetStructure VALUES('1. NON CURRENT ASSETS','Right of use Asset','4')
INSERT INTO PBI.BalanceSheetStructure VALUES('1. NON CURRENT ASSETS','Deferred Tax Assets','5')
INSERT INTO PBI.BalanceSheetStructure VALUES('1. NON CURRENT ASSETS','Computer software and hardware','6')
INSERT INTO PBI.BalanceSheetStructure VALUES('2. CURRENT ASSETS','Stock','7')
INSERT INTO PBI.BalanceSheetStructure VALUES('2. CURRENT ASSETS','Trade receivables','8')
INSERT INTO PBI.BalanceSheetStructure VALUES('2. CURRENT ASSETS','Loan Receivable','9')
INSERT INTO PBI.BalanceSheetStructure VALUES('2. CURRENT ASSETS','Provision','10')
INSERT INTO PBI.BalanceSheetStructure VALUES('2. CURRENT ASSETS','Deposits & prepayments','11')
INSERT INTO PBI.BalanceSheetStructure VALUES('2. CURRENT ASSETS','Accrued income','12')
INSERT INTO PBI.BalanceSheetStructure VALUES('2. CURRENT ASSETS','Deferred exp','13')
INSERT INTO PBI.BalanceSheetStructure VALUES('2. CURRENT ASSETS','VAT','14')
INSERT INTO PBI.BalanceSheetStructure VALUES('2. CURRENT ASSETS','Other receivable','15')
INSERT INTO PBI.BalanceSheetStructure VALUES('2. CURRENT ASSETS','Intercompany balances','16')
INSERT INTO PBI.BalanceSheetStructure VALUES('2. CURRENT ASSETS','Cash in hand and at bank','17')
INSERT INTO PBI.BalanceSheetStructure VALUES('3. CURRENT LIABILITIES','_Intercompany balances','18')
INSERT INTO PBI.BalanceSheetStructure VALUES('3. CURRENT LIABILITIES','Trade creditors','19')
INSERT INTO PBI.BalanceSheetStructure VALUES('3. CURRENT LIABILITIES','Deferred income','20')
INSERT INTO PBI.BalanceSheetStructure VALUES('3. CURRENT LIABILITIES','Other creditors and accruals','21')
INSERT INTO PBI.BalanceSheetStructure VALUES('3. CURRENT LIABILITIES','Payable to clients','22')
INSERT INTO PBI.BalanceSheetStructure VALUES('3. CURRENT LIABILITIES','_VAT','23')
INSERT INTO PBI.BalanceSheetStructure VALUES('3. CURRENT LIABILITIES','Loan Payable','24')
INSERT INTO PBI.BalanceSheetStructure VALUES('3. CURRENT LIABILITIES','Lease Liabilities','25')
INSERT INTO PBI.BalanceSheetStructure VALUES('3. CURRENT LIABILITIES','Directors current a/cs','26')
INSERT INTO PBI.BalanceSheetStructure VALUES('3. CURRENT LIABILITIES','Tax liability','27')
INSERT INTO PBI.BalanceSheetStructure VALUES('4. NET ASSETS','','28')
INSERT INTO PBI.BalanceSheetStructure VALUES('5. SHARE CAPITAL AND RESERVES','Issued share capital','29')
INSERT INTO PBI.BalanceSheetStructure VALUES('5. SHARE CAPITAL AND RESERVES','Retained Earnings','30')
INSERT INTO PBI.BalanceSheetStructure VALUES('5. SHARE CAPITAL AND RESERVES','Other Reserves','31')
INSERT INTO PBI.BalanceSheetStructure VALUES('5. SHARE CAPITAL AND RESERVES','Capital Contribution','32')
INSERT INTO PBI.BalanceSheetStructure VALUES('5. SHARE CAPITAL AND RESERVES','P&L for period','33')
