CREATE TABLE PBI.PLAnalysisStructure(
 Level1 VARCHAR(100)
,Level2 VARCHAR(100)
,Level0 VARCHAR(100)
,Ord TINYINT
)


INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('1. Profit/(loss) from operations', '1. Income','Interest Income ','1')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('1. Profit/(loss) from operations', '1. Income','Income from car Sale','2')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('1. Profit/(loss) from operations', '1. Income','Commision','3')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('1. Profit/(loss) from operations', '1. Income','Membership Fees','4')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('1. Profit/(loss) from operations', '1. Income','Acquisition Fees','5')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('1. Profit/(loss) from operations', '1. Income','Purchase Fee','6')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('1. Profit/(loss) from operations', '1. Income','Other Income','7')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('1. Profit/(loss) from operations', '1. Income','Government Grants','8')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('1. Profit/(loss) from operations', '2. Direct expenses','Insurance Management','9')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('1. Profit/(loss) from operations', '2. Direct expenses','Service Management','10')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('1. Profit/(loss) from operations', '2. Direct expenses','Tire Management','11')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('1. Profit/(loss) from operations', '2. Direct expenses','Road tax Management','12')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('1. Profit/(loss) from operations', '2. Direct expenses','Other vehicle expenses','13')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('1. Profit/(loss) from operations', '2. Direct expenses','Car purchase','14')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('1. Profit/(loss) from operations', '2. Direct expenses','Loss on Sale','15')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('1. Profit/(loss) from operations', '2. Direct expenses','Loss from insurance claim','16')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES(NULL, '3. Operating profit/(loss)','','17')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Salaries and contributions','18')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Rent','19')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Legal and professional fees','20')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Accountants','21')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Licenses','22')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Postages and courier','23')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Lighting and heating','24')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Website expenses','25')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Computer expenses','26')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Software Expenses','27')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Stamp duty','28')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','_Advertising','29')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Donations','30')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Domain Expenses','31')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Subscriptions','32')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Office Expenses','33')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Audit','34')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Cleaning','35')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Printing and stationery','36')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Repairs and maintenance','37')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Internet and telephone expenses','38')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Car expenses','39')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Annual levy','40')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Entertainment','41')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Sundry expenses','42')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Municipality taxes','43')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Depreciation and amortisation','44')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '4. Administration expenses','Staff Expenses','45')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '5. Selling expenses','Advertising ','46')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '5. Selling expenses','Marketing materials','47')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '5. Selling expenses','Exhibitions','48')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '5. Selling expenses','Transportation expenses','49')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '5. Selling expenses','Travelling & accommodation','50')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '5. Selling expenses','Bad debts written off','51')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '5. Selling expenses','Clients compensations','52')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '5. Selling expenses','Customers entertainment','53')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES(NULL, '6. Financing expenses','Bank Charges','54')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES(NULL, '6. Financing expenses','Foreign Exchange difference','55')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES(NULL, '6. Financing expenses','Interest expense','56')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES(NULL, '6. Financing expenses','Exchange difference','57')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES(NULL, '6. Financing expenses','Tax interest and penalties','58')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES(NULL, '6. Financing expenses','Other interest','59')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES(NULL, '6. Financing expenses','Intercompany interest','60')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('3. EBITDA',NULL, NULL,61)
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('2. Total other expenses', '6.  Financing expenses',NULL,'67')
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('4. Loan interest', NULL, NULL,62)
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('5. EARNINGS after interest',NULL, NULL,63)
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('6. Exchange difference',NULL, NULL,64)
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('7. Earnings after exchange difference',NULL, NULL,65)
INSERT INTO PBI.PLAnalysisStructure (Level0, Level1, Level2,Ord) VALUES('8. Adjustments',NULL, NULL,66)
                                                      